services:
  api:
    build: .
    container_name: phonebook-api
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/phonebook
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: phonebook-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: phonebook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
